### ISSUE TITLE
Add notes to phendata.R

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/heattolerance#1]
In particular, why do we have this code:

d$days[d$days == "8"] <- "7"
d$days[d$days == "15"] <- "14"
d$days[d$days == "18"] <- "17"
d$days[d$days == "22"] <- "21"
d$days[d$days == "25"] <- "24"
d$days[d$days == "36"] <- "35"
d$days[d$days == "66"] <- "65"
d$days[d$days == "67"] <- "65"
d$days[d$days == "74"] <- "73"
d$days[d$days == "80"] <- "79"
d$days[d$days == "87"] <- "86"
d$days[d$days == "88"] <- "86"
d$days[d$days == "94"] <- "93"

**Comment by merrilln** [comment]
This was to correct for the fact that not all of the plants could be sampled in one day, so the code was calculating averages per day, and if the second day plants were not developing as quickly as the first day plants, it would look like the average was dropping.

**Comment by lizzieinvancouver** [comment]
Done! See commit: 5369c2cb4c8d9f1aa2be47c28440b5033893f689
